TOP=../..
include $(TOP)/configure/CONFIG

DB_INSTALLS += $(ASYN)/db/asynRecord.db
DB_INSTALLS += $(AUTOSAVE)/asApp/Db/save_restoreStatus.db

DB += keithley2001.db
DB += keithley6221.db
PROTO += keithley2001.proto
PROTO += keithley6221.proto

DB += moellermeter.db
PROTO += moellermeter.proto

include $(TOP)/configure/RULES

