# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 20480);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.defaultenginename.US", "Google");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160303075611");
user_pref("browser.slowStartup.averageTime", 1602);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage", "https://www.jlab.org/Hall-B/");
user_pref("browser.startup.homepage_override.buildID", "20160303075611");
user_pref("browser.startup.homepage_override.mstone", "38.7.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1465305113413");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1465218774427");
user_pref("datareporting.policy.firstRunTime", "1465218713413");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1170);
user_pref("datareporting.sessions.current.main", 340);
user_pref("datareporting.sessions.current.sessionRestored", 1383);
user_pref("datareporting.sessions.current.startTime", "1465219073416");
user_pref("datareporting.sessions.current.totalTime", 6);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1465218712409,\"a\":17,\"t\":86,\"c\":true,\"m\":370,\"fp\":1814,\"sr\":2006}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1465218799815,\"a\":17,\"t\":87,\"c\":true,\"m\":310,\"fp\":1406,\"sr\":1475}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.7.0");
user_pref("extensions.lastAppVersion", "38.7.0");
user_pref("extensions.lastPlatformVersion", "38.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.7.0\",\"st\":1457965913000,\"mt\":1457010273000}}}");
user_pref("gecko.buildID", "20160303075611");
user_pref("gecko.mstone", "38.7.0");
user_pref("media.gmp-manager.buildID", "20160303075611");
user_pref("media.gmp-manager.lastCheck", 1465218862);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.proxy.type", 4);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1465219073);
user_pref("toolkit.telemetry.previousBuildID", "20160303075611");
