//Variables to hole the data from the template files
TString **AllLinesDB;       //hold the lines in the file
Int_t NlinesDB=1;            //no of lines in the file - editors start numbering at L1
TString **AllLinesGUI;      //hold the lines in the file
Int_t NlinesGUI=1;           //no of lines in the file - editors start numbering at L1

//Variables to hold the data for the detector elements.
Int_t    nElem=0;
Double_t xpos[500];
Double_t ypos[500];
int xp[500];
int yp[500];
int hits[500];
Int_t    xid[500];
Int_t    yid[500];
Int_t    flashid[500];
Int_t    scalerid[500];



void makeDBandGUI(Char_t *TemplateFileNameDB,Char_t *TemplateFileNameGUI, Int_t dumpLinesOnly=0){
  FILE *fpDB;
  FILE *fpGUI;
  Char_t line[420];
  Char_t filenameDB[200];
  Char_t filenameGUI[200];
  
  //Start by storing the template files ***********************************************************
  fpDB=fopen(TemplateFileNameDB,"r");              //open once to count lines
  while(fgets(line,400,fpDB) != NULL){  	   // check got a line from file
    NlinesDB++;
  }
  fclose(fpDB);
  AllLinesDB = new TString*[NlinesDB];
  
  NlinesDB=1;                                      //Since editors start numbering at line 1
  fpDB=fopen(TemplateFileNameDB,"r");              //open once to read lines
  cout << "Listing for TemplateFileNameDB" << endl;
  while(fgets(line,400,fpDB) != NULL){  	   // check got a line from file
    AllLinesDB[NlinesDB]= new TString(line);
    cout << "L" << NlinesDB<< ":   " <<AllLinesDB[NlinesDB]->Data();
    NlinesDB++;
  }
  fclose(fpDB);

  cout << endl << endl;

  fpGUI=fopen(TemplateFileNameGUI,"r");            //open once to count lines
  while(fgets(line,400,fpGUI) != NULL){  	   // check got a line from file
    NlinesGUI++;
  }
  fclose(fpGUI);
  AllLinesGUI = new TString*[NlinesGUI];
  
  NlinesGUI=1;                                            //Since editors start numbering at line 1
  fpGUI=fopen(TemplateFileNameGUI,"r");              //open once to read lines
  cout << "Listing for TemplateFileNameGUI" << endl;
  while(fgets(line,400,fpGUI) != NULL){  		// check got a line from file
    AllLinesGUI[NlinesGUI]= new TString(line);
    cout << "L" << NlinesGUI<< ":   " <<AllLinesGUI[NlinesGUI]->Data();
    NlinesGUI++;
  }
  fclose(fpGUI);

  if(dumpLinesOnly) return;
  // end of section storing the template files ************************************************************


  //Run the detector algorithm to fill these variables - declared as global at the top. *******************
  //Int_t    nElem=0;
  //Double_t xpos[500];
  //Double_t ypos[500];
  //Int_t    xid[500];
  //Int_t    yid[500];
  //Int_t    flashid[500];
  //Int_t    scalerid[500];
  //..... etc

  generateFTLayout();  //Run the detector algorithm function at the bottom here
  // ******************************************************************************************************

  //Open the corresponding output files fill them based on the detector specific algorithm ****************
  //
  //This requires looking at the template files and figuring out which lines need to be cloned, 
  //and what needs tobe replaced etc.
  //Either open the templates in emacs, or run this function with dumpLinesOnly=1 to see the line numbers

  //DB file
  //make new names for the output file, open in write mode

  sprintf(filenameDB,"%s.cloned",TemplateFileNameDB);
  fpDB=fopen(filenameDB,"w"); 

  //Copy the 1st part from the template.
  for(Int_t n=1;n<=8;n++){                //1st part of db file
    fprintf(fpDB,"%s",AllLinesDB[n]->Data());
  }

  //Create a lot of lines according to some algorithm
  fprintf(fpDB,"#The following lines (until ### end of autogen ###) were autogenerated from a script\n#\n");
  //do the lines for all the elements
  for(int n=0;n<nElem;n++){
    fprintf(fpDB,"   {\"B_FT_FLASHER\",\"L0\",\"%d\",\"%d\",\"%d\"}\n",scalerid[n],xid[n],yid[n]);
  }
  fprintf(fpDB," ### end of autogen ###\n#\n");

  //copy the remaining lines from the template.
  for(Int_t n=10;n<=10;n++){                //1st part of db file
    fprintf(fpDB,"%s",AllLinesDB[n]->Data());  
  }

  //GUI file
  sprintf(filenameGUI,"%s.cloned",TemplateFileNameGUI);
  fpGUI=fopen(filenameGUI,"w");
  for(Int_t n=1;n<=51;n++){                //1st part of opi file
    fprintf(fpGUI,"%s",AllLinesGUI[n]->Data());
  }
  
}


void generateFTLayout(){   //using information from Rafaella's spreadsheet;
  Double_t x,y,D,R;
  Int_t n=0;
  Int_t f=0;

  //This describes the layout of the caloromiter elements.

  D=15.3;
  
  for(int idx=-11;idx<=11;idx++){
    for(int idy=-11;idy<=11;idy++){
      if((idx==0)||(idy==0)) continue;

      if(idx>0)x=(idx-0.5);else x=(idx+0.5);
      if(idy>0)y=(idy-0.5);else y=(idy+0.5);
      
      R=TMath::Sqrt(x*x + y*y)*D;
      x*=D;y*=D;

      if((60.0<R)&&(R<168.3)){
	xpos[n]=x/D; ypos[n]=y/D; xid[n]=idx; yid[n]=idy; flashid[n]=n; scalerid[n]=n;
	n++;
      }      
    }
  }
  nElem=n;
}

void makeDb(const Char_t* Prefix="${Prefix}", int nled=336){
  generateFTLayout3();
  cout << "#Paste these lines into the init file for the flasher" << endl;
  cout << "# x and y coord tables" << endl;
  cout << "caput -a " << Prefix<<":X_TABLE " << nled;
  for(int id=0;id<nled;id++){
    cout << " " << xp[id];
  }
  cout << endl;  
  cout << "caput -a " << Prefix<<":Y_TABLE " << nled;
  for(int id=0;id<nled;id++){
    cout << " " << yp[id];
  }
  cout << endl;  
}


void generateFTLayout2(int nled){   //using information from Rafaella's spreadsheet;
  Float_t D=15.3;
  Float_t R;
  
  int id=0;
  for(int y=-11;y<=11;y++){
    for(int x=-11;x<=11;x++){
      if((x==0)||(y==0)) continue;
      xp[id]=x;
      yp[id]=y;
      
      R=TMath::Sqrt(x*x + y*y)*D;
      if((69.0<R)&&(R<179.0)) hits[id]=1;
      else {
	xp[id]=999;
	yp[id]=999;
	hits[id]=999;
      }
      cout << "ID,hit,R = " << id << ", " << hits[id] << ", " << R << endl;
      id++;
      if (id>=nled) return;
    }
  }
}

void generateFTLayout3(){
  Float_t D=15.3;
  Float_t R;
  
  int id=0;
  for(int y=-11;y<=11;y++){
    for(int x=-11;x<=11;x++){
      if((x==0)||(y==0)) continue;
      R=TMath::Sqrt(x*x + y*y)*D;
      if((69.0<R)&&(R<179.0)){
	xp[id]=x;
	yp[id]=y;
	id++;
      }
    }
  }
}
