TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
#DB += $(wildcard ../*.db)
#DB += $(wildcard ../*.substitutions)
#DB += $(wildcard ../sums/*.db)
#DB += $(wildcard ../subs/*.substitutions)
#DB += $(wildcard ../wf/*.db)
#DB += $(wildcard ../wf/*.substitutions)

BEAST += jscalers-alarm.xml

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

