TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += OmegaCYD218.db
DB += OmegaCYD218_ch.db

PROTO += OmegaCYD218.proto
REQ   += OmegaCYD218_settings.req
REQ   += OmegaCYD218_chN_settings.req

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

