#!../../bin/linux-x86/richsim
#
#This file was autogenerated by mkHVEpics on: Wed Jun 15 17:12:02 2016
#Crate name: RICH
#

< envPaths
epicsEnvSet("IOC","iocrichsim")

cd ${TOP}

dbLoadDatabase("dbd/richsim.dbd")
richsim_registerRecordDeviceDriver(pdbbase)

## Register all support components
# call to run sy1527Init()

# Start_CAEN - call to run sy1527Start(), sy1527GetMap(), sy1527PrintMap()

# HVECAL1 ###

## Load record instances

dbLoadRecords("$(DEVIOCSTATS)/db/iocAdminSoft.db", "IOC=$(IOC
dbLoadRecords("${AUTOSAVE}/asApp/Db/save_restoreStatus.db", "P=${IOC}:")
dbLoadRecords("db/richGasCooling.db")
dbLoadRecords("db/richN2Gas.db")
dbLoadTemplate("db/HVRICH.substitutions")
dbLoadTemplate("db/TEMPRICH.substitutions")
dbLoadTemplate("db/LVRICH1.substitutions")

#dbLoadTemplate("db/HVECAL1_ECAL.substitutions")
#dbLoadTemplate("db/HVECAL1_LTCC.substitutions")

#PVs for unused slots, channels which may be available in the above crates
#Comment in as required

#dbLoadTemplate("db/HVECAL1_SPARES.substitutions")

cd ${TOP}/iocBoot/${IOC}

##autosave setup
< save_restore.cmd

iocInit

##autosave startup
##Handle autosave 'commands' contained in loaded databases.
makeAutosaveFiles()
create_monitor_set("info_positions.req",5,"P=$(IOC):")
create_monitor_set("info_settings.req",30,"P=$(IOC):")

dbDumpRecord > st.cmd.RICH.dump
