TOP=../..
include $(TOP)/configure/CONFIG

DB_INSTALLS += $(ASYN)/db/asynRecord.db
DB_INSTALLS += $(AUTOSAVE)/asApp/Db/save_restoreStatus.db

DB += A6551.db
DB += A6621.db
PROTO += A6551.proto
PROTO += A6621.proto

DB += dclv.substitutions

REQ += A6621_settings.req

BEAST += dclv.xml

include $(TOP)/configure/RULES

