TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += mmgas_asyn_aiFloat64.template
DB += mmgas_asyn_bo_bit.template

DB += mmgas_bmt.substitutions
DB += mmgas_fmt.substitutions
DB += mmgas_ftt.substitutions

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

