#!/usr/bin/python
from clas12NodesDict import *
import argparse
import datetime


#This is a template for how to a run a command on the whole hierarchy of nodes from a starting point downwards.
#The doNode() function does the work
#It calls functions here as apropriate:

#The following 4 functions need to be defined.
#main():             to do any initialisation
#start_node():       called for every node before do_unto_elememt() is applied to all its elements    
#do_unto_element():  called for every element
#end_node():         called for every node after do_unto_elememt()  is applied to all its elements    

topName=""

#This makes the .xml for setting up an alarm

def main():
    global topName
    parser = argparse.ArgumentParser()
    parser.add_argument("top", help="Top node (eg B_HV). To see all nodes do ./dumpTree.py B")
    parser.add_argument("topname", help="Top node name - a nice name in quotes (eg \"High voltage\")")
    parser.add_argument("confname", help="Name of Alarm configuration - almost certainly HallB")
    args        = parser.parse_args()
    topnode     = args.top
    topName = args.topname
    configName  = args.confname

    now = datetime.datetime.now()
    print "<!--"
    print "   Alarm config generated by makeAlarmConfig.py on "+now.strftime("%Y-%m-%d %H:%M")
    print "-->"
    print "<config name=\""+configName+"\">"
    
    #This is the function that works recursively through the tree and calls do_unto_element start_node end_node
    doNode(topnode, "", 0, "")

    print"</config>"

def start_node(node,parent,depth,indent):
    global topName
    if(depth==0):
        print indent+"  <component name=\""+topName+"\">"
    else:
        print indent+"  <component name=\""+node+"\">"
    return

def end_node(node,parent,depth,indent):
    print indent+"   </component>"
    return

def do_unto_element(element,parent,depth,indent):
    print indent+"   <pv name=\""+parent+"_"+element+".STAT\">"
    print indent+"      <description>High Voltage alarm for "+parent+"_"+element+"</description>"
    print indent+"      <latching>true</latching>"
    print indent+"      <annunciating>true</annunciating>"
    print indent+"      <delay>2.0</delay>"
    print indent+"      <count>0</count>"
    print indent+"      <guidance>"
    print indent+"         <title>Guidance</title>"
    print indent+"         <details>Try to reset the voltage channel using the GUI. If problem persists, contact the expert.</details>"
    print indent+"      </guidance>"
    print indent+"      <display>"
    print indent+"         <title>Open HV GUI</title>"
    print indent+"         <details>/CSS/HV2/ntree.opi   &quot;node="+parent+"&quot;</details>"
    print indent+"      </display>"
    print indent+"   </pv>"

    return


#########################################################################################
# Recursion begins here
# Do not edit below here unless you know are prepared to disappear up your own arse     #
# Kenneth
#########################################################################################

def doNode( node, parent, depth, indent):
    thisnode = node
    if(depth>0):
        thisnode = parent+"_"+node
    subnodes = SubNodeNames[thisnode].split()
    elements = ElementNames[thisnode].split()
        
    start_node( node, parent, depth, indent)

    for s in subnodes:
        doNode( s, thisnode, depth+1,indent+"  ")        
               
    for e in elements:
        do_unto_element(e, thisnode, depth, indent+"  ")

    end_node ( node, parent, depth, indent )
        
    return
    
if __name__ == "__main__": main()

