#!/bin/sh

#subs=`ls ../../db/HV*_*.substitutions`
subs=`ls ../../db/HV*_ECAL.substitutions ../../db/HV*_FTOF.substitutions `

today=`date`
echo "Subslist for parsing generated by $0  on ${today}" > sub2dump.log

for s in $subs;
do
    msi -S $s
    echo $s >> sub2dump.log
done

exit
