#!/bin/sh

export JAVA_HOME=/usr/lib/jvm/java-1.8.0-oracle
export PATH=$JAVA_HOME/bin:$PATH

#ROOT=$1

EXE_DIR=/usr/clas12/css/4.3.3/linux-x86_64/bin
INI_DIR=/usr/clas12/release/pro/epics/tools/beast
XML_DIR=/usr/clas12/release/pro/epics/apps/beast

$EXE_DIR/JMS2RDB -pluginCustomization $INI_DIR/jms2rdb_settings.ini
