#!/bin/sh

export JAVA_HOME=/usr/lib/jvm/java-1.8.0-oracle
export PATH=$JAVA_HOME/bin:$PATH

EXE_DIR=/usr/clas12/css/pro/linux-x86_64/bin
INI_DIR=/usr/clas12/release/pro/epics/tools/beast
XML_DIR=/usr/clas12/release/pro/epics/apps/beast

WORKSPACE=/tmp/Annunciator.$$

# it works from here:
#/usr/clas12/epics/css-clas12-4.1.1/x86_64/annunciator-4.0.101
EXE_DIR=/usr/clas12/epics/css-clas12-4.1.1/x86_64/AlarmAnnunciator_3.1.7
cd $EXE_DIR

# Start Headless Annunciator
./JMS2SPEECH -pluginCustomization $INI_DIR/annunciator_settings.ini -data $WORKSPACE

