#!/bin/sh

export JAVA_HOME=/usr/lib/jvm/java-1.8.0-oracle
export PATH=$JAVA_HOME/bin:$PATH

ROOT=HallB

EXE_DIR=/usr/clas12/css/dev/linux-x86_64/bin
INI_DIR=/usr/clas12/release/pro/epics/tools/beast
XML_DIR=/usr/clas12/release/pro/epics/apps/beast

# Start Server
$EXE_DIR/AlarmServer -root $ROOT -pluginCustomization $INI_DIR/alarm_settings.ini
