#!/bin/bash
export DISPLAY=:0
export JAVA_HOME=/usr/clas12/third-party-libs/jdk/1.8.0_31
export PATH=$JAVA_HOME/bin:$PATH
EXE_DIR=/usr/clas12/css/4.3.3/linux-x86_64/bin
INI_DIR=/usr/clas12/epics/el9/clas12/tools/beast

$EXE_DIR/JMS2RDB -pluginCustomization $INI_DIR/jms2rdb_settings.ini
